# This is a basic workflow to help you get started with Actions

name: Appcast


on:
  
  workflow_dispatch:

jobs:

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
     
          
      - name: Rebuild 🚀 
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PERSONAL_TOKEN }}
          script: |
            github.rest.repos.requestPagesBuild({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })

          
