name: Mars

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

env:
  SPARKLE_KEY: ${{ secrets.SPARKLE_KEY }}
  PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
  BARK_KEY: ${{ secrets.BARK_KEY }}
  BARK_HOST: ${{ secrets.BARK_HOST }}
  BARK_ICON: https://raw.githubusercontent.com/ZzzM/CalendarX/master/CalendarX/Assets.xcassets/AppIcon.appiconset/icon_128x128.png

jobs:

  Release:
    runs-on: macos-13
    steps:

    - name: Checkout
      uses: actions/checkout@v4.1.1
      
    - name: Setup
      uses: actions/setup-node@v4.0.0
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1.6.0

    - name: Create DMG
      run: |
        fastlane create_dmg

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        body_path: ${{ env.LOG_PATH }}
        files: ${{ env.APP_PATH }}

    - name: Appcast
      uses: actions/github-script@v7.0.1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        github-token: ${{ env.PERSONAL_TOKEN }}
        script: |
          github.rest.repos.requestPagesBuild({
            owner: context.repo.owner,
              repo: context.repo.repo,
            })
            
    - name: Bark
      uses: monlor/bark-action@v3
      if: success() || failure()
      with:
        key: ${{ env.BARK_KEY }}
        host: ${{ env.BARK_HOST }}
        title: ${{ env.APP_NAME }} - ${{ env.APP_VERSION }}
        body: ${{ job.status }}
        icon: ${{ env.BARK_ICON }}
        sound: alarm
        isArchive: 1
